services:
  diva_ktor_server:
    image: diva_ktor_server:dev
    container_name: diva_ktor_server
    build:
      context: .
      dockerfile: Dockerfile
    command: ["java", "-jar", "./bin/diva-ktor-server.jar"]
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      DOMAIN: ${DOMAIN}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_REALM: ${JWT_REALM}
      KTOR_ENV: ${KTOR_ENV}
    depends_on:
      diva_db:
        condition: service_healthy
    volumes:
      - ./server:/app/server
      - ./auth/api/auth-api-handler:/app/auth/api/auth-api-handler
      - ./auth/data/auth-data-server:/app/auth/data/auth-data-service
      - ./auth/data/auth-data-shared:/app/auth/data/auth-data-shared
      - ./auth/database/auth-database-server:/app/auth/database/auth-database-server
      - ./auth/database/auth-database-shared:/app/auth/database/auth-database-shared
      - ./auth/di/auth-di-server:/app/auth/di/auth-di-server
      - ./auth/models:/app/auth/models
      - ./core/models:/app/core/models
      - ./core/database/postgres:/app/core/database/postgres
      - ./build-logic:/app/build-logic
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
      - ./gradle.properties:/app/gradle.properties
      - ./gradle:/app/gradle
    networks:
      - net
  diva_db:
    container_name: diva_db_dev
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - net
volumes:
  db_data:
    driver: local
networks:
  net:
    driver: bridge