ktor:
    environment: $?KTOR_ENV
    application:
        modules:
            - com.diva.server.ApplicationKt.module
    deployment:
        port: ${PORT:8080}
        domain: ${DOMAIN:localhost}
        watch: [ classes, resources ]
database:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    name: ${DB_NAME:diva}
    schema: ${DB_SCHEMA:public}
jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    realm: ${JWT_REALM}
mail:
    apiKey: ${RESEND_API_KEY}
    fromEmail: ${RESEND_FROM_EMAIL}